@startuml

(Altitude Control System)
skinparam packageStyle rectangle

:Databases:

rectangle DataSources {
  :Databases: <-down- (DataSources) : Provides Data
  :Dynamic Data:
  :Static Data:
}

rectangle -AirportList- {
   json Static_Data {
     "Airport": "Location",
     "Airspace": "Req Altitude",
     "Airspace": "Size"
   }
}

:-AirportList-: -up-> :Static Data:

rectangle OpenSkyNetwork_API {
   json Dynamic_Data {
     "Aircraft": "Location",
     "Aircraft": "Geo Altitude",
     "Aircraft": "Callsign"
   }
}

:OpenSkyNetwork_API: -up-> :Dynamic Data:

json DB {
"MongoDB": "Dynamic Data",
"Neo4J": "Dynamic Data",
"Redis": "Static Data"
}

:Databases: .left. DB
:Databases: -right-> (Altitude Control System) : Updates Data

:Pilot:

:Air Traffic Control: <-up- :Flight Supervisor: : Informs
:Air Traffic Control: -right-> :Pilot: : Alerts 

:Flight Supervisor: <-up-> (Altitude Control System) : Operates

(Altitude Control System) -right-> (Warning)

"Throws Alert" as (Warning)

(Warning) -down-> :Flight Supervisor: : Notifies

json System_Actions {
  "Function": "Search Area",
  "Function": "Use Filters",
  "Function": "Handle Warnings"
}

:System_Actions: .up. :Altitude Control System:
:System_Actions: .right. :Flight Supervisor:

@enduml