@startuml
skinparam packageStyle rectangle
'layout
left to right direction

'actors
actor "Flight Supervisor" as FS
actor "Air Traffic Control" as ATC
actor "Pilot" as Pilot

'system
rectangle "Altitude Control System" {
    usecase "Update Data to Altitude Control System" as UC1
    usecase "Provides Data in Altitude Control System" as UC2
    usecase "Operate Altitude Control System" as UC3
    usecase "Handle Warnings" as UC4
}

FS <-down- UC1 : "Fetches"
UC2 <-up- UC1 : "<<includes>>"
FS -right-> UC3 : "Operates"
FS -right-> UC4 : "Handles Warnings"
UC4 -left-> FS : "Notifies"
ATC -down-> Pilot : "Alerts Pilot"
ATC <-right- FS : "Informs and Alerts"
@enduml