@startuml heatmap

left to right direction

actor User as user

 
usecase "View Real-time Leaderboard/Heatmap" as view_real_time
usecase "View Historical Leaderboard/Heatmap" as view_historical
usecase "Leaderboard/Heatmap Filter" as filter

user --> view_real_time
user --> view_historical
user --> filter

view_real_time <-- view_historical : <<extends>>

note bottom of filter: Filter by time range

note left of view_real_time
Based on simulated data:
* Top 10 airports, routes
* Heatmaps: airports, routes
end note

@enduml
